version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest
    working_directory: ~/repo
    steps:
      - setup_remote_docker
      - run: sudo apt install libboost-dev
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: scripts/build.sh
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
  deploy:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: scripts/deploy.sh bitsum 10cc5092cb4d674c33b5 $BITSUM_GITHUB_CLIENT_SECRET
      - run: scripts/deploy.sh leviarcoin c0d8828df1ed3e2df214 $LEVIARCOIN_GITHUB_CLIENT_SECRET
      - run: scripts/deploy.sh fonero 6d839065d4608de7a6eb $FONERO_GITHUB_CLIENT_SECRET
      - run: scripts/deploy.sh intensecoin af00bb97f7bfa8717658 $INTENSECOIN_GITHUB_CLIENT_SECRET
      - run: scripts/deploy.sh edollar fc9a1485c6a4f02e7bb1 $EDOLLAR_GITHUB_CLIENT_SECRET

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
            branches:
              ignore: production
      - deploy:
          filters:
            branches:
              only: production
