version: 2
jobs:
  build:
    - setup_remote_docker
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: scripts/build.sh
  deploy:
    steps:
      - checkout
      - run: scripts/deploy.sh

workflows:
  version: 2
    build-test-and-approval-deploy:
      jobs:
        - build
        - hold:
            type: approval
            requires:
             - build
        - deploy:
            branches:
              only: production
            requires:
              - hold
