version: 2
jobs:
  build:
    type: docker
    docker:
      - image: circleci/node:latest
    working_directory: ~/repo
    steps:
      - run: sudo apt install libboost-dev
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: scripts/build.sh
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
  deploy:
    steps:
      - setup_remote_docker
      - checkout
      - run: scripts/deploy.sh

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - hold:
          type: approval
          requires:
           - build
      - deploy:
          filters:
            branches:
              only: production
          requires:
            - hold
