version: 2
jobs:
  build:
    - setup_remote_docker
    docker:
      - image: circleci/node:latest
    working_directory: ~/repo
    steps:
      - run: sudo apt install libboost-dev
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: scripts/build.sh
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
  deploy:
    steps:
      - checkout
      - run: scripts/deploy.sh

workflows:
  version: 2
    build-test-and-approval-deploy:
      jobs:
        - build
        - hold:
            type: approval
            requires:
             - build
        - deploy:
            branches:
              only: production
            requires:
              - hold
